# Site settings
title: KORA
description: KORA is an AI-powered platform that personalizes learning, helping students and educators succeed.
baseurl: ""
url: "https://kora-edu.github.io"

# User settings
username: KORA 
user_description: KORA is an AI-driven academic platform designed to enhance learning by generating personalized study resources, practice exams, and real-time feedback. Our mission is to help students study smarter, not harder, and to support educators in creating more effective learning environments.
user_title: Generative Academic AI for Students and Educators
email: contact@kora-edu.com
twitter_username: kora_edu
github_username: kora-edu
gplus_username: kora_edu

# Google-analytics
google-analytics:
  id: "" # Add your Google Analytics ID here if you have one

exclude: ['package.json', 'src', 'node_modules']
