# Site settings
title: KORA | Dev blog
description: "Academic generative goodness!"
url: "https://kora-edu.com" # Your custom domain URL
baseurl: "" # Leave blank when using a custom domain

author:
  name: "KORA"
  email: "koraedu.team@gmail.com"
  url: "https://kora-edu.com"

# Build settings
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
markdown: kramdown

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
